version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.3
        environment:
          MIX_ENV: test

    working_directory: ~/liveness

    steps: 
      - checkout 
      - run: mix format --check-formatted
      - run: mix test
